### PR TITLE
(#3) Add message input box

### PR DESCRIPTION
**Pull request by bonniesimon**
I've added a new textbox for inputting the message. Then I converted the inputted string to a URL-encoded string. 
Then I added it to the URL.

I deployed my fork on vercel and it works fine.

### CODE REVIEW

**Comment by bonniesimon** [comment]
@ninest Can you please review this?

**Comment by bonniesimon** [comment]
@ninest 🧐

**Comment by ninest** [comment]
I'm so sorry, I don't know how I missed this for 3 years. I really appreciate the PR and thank you for notifying me again!

**Review by ninest — APPROVED** [review]

**Review by ninest — APPROVED** [review]

**Comment by ninest** [comment]
It seems I'm getting this error

```
Merge attempt failed
Head branch is out of date. Review and try the merge again.
```

Do you mind making a new branch? If not, I can add in the changes manually

**Comment by bonniesimon** [comment]
Thanks, I'll make the change. I would love this to be my first contribution.

**Comment by bonniesimon** [comment]
@ninest I've made another PR #4 
Please check

**Pull request closed without merging**
